bnn_fc1_index: '0'
bnn_fc2_index: '0'
bnn_fc3_index: '0'
bnn_weights_folder: C:/Users/Emilie Ye/OneDrive/Desktop/isure/weightFolder/BNNWeight
device_data_file: C:/Users/Emilie Ye/OneDrive/Desktop/isure/probabilistic-memory-tool-main/jupyter/simulator/sampled_weights_fc1.csv
frequency: 1e9
mode: Memory
nn_weights_folder: C:/Users/Emilie Ye/OneDrive/Desktop/isure/weightFolder/NNWeight
precision_mu: '1'
precision_sigma: '1'
sampling_times: '100'
technology: '0'
weight: A
