Metal0_unitwireresis: 1179138.322198924
Metal1_unitwireresis: 1179138.322198924
accessVoltage: 1.1
accesstype: CMOS_access
alpha: 1.44
barrierthickness: 7.0e-09
beta: 1.4
cellBit: 2
cell_type: SRAM
delta: 0.15
deviceroadmap: HP
epsilon: 0.05
gamma: 0.5
heightInFeatureSize: 10
heightInFeatureSize1T1R: 4
heightInFeatureSizeCrossbar: 2
heightInFeatureSizeSRAM: 10
minSenseVoltage: 0.1
numColSubArray: 128
numRowSubArray: 128
operationmode: conventionalSequential
readPulseWidth: 1.0e-08
readVoltage: 0.51
resistanceOff: 102000.0
resistanceOn: 6000.0
transistortype: conventional
tsvCap: 2.0e-14
tsvPitch: 1.7e-06
tsvRes: 0.3
unitLengthWireResistance: 1179138.322198924
validated: false
widthAccessCMOS: 1
widthInFeatureSize: 28
widthInFeatureSize1T1R: 12
widthInFeatureSizeCrossbar: 2
widthInFeatureSizeSRAM: 28
widthSRAMCellNMOS: 2
widthSRAMCellPMOS: 1
wireResistanceColPerCell: 3.466666667264836
wireResistanceRowPerCell: 1.2380952383088701
wireWidth: 105
writeVoltage: 2
zeta: 1.22
