bins: 50
mode: Demo
mus:
- 1.0
- 1.0
- 1.0
rng_file: C:/Users/EmilieYe/isure/code/PROMISE/Data/currents_vlsi.csv
rng_source: Choose file
sampling_times: 100
sigmas:
- 1.0
- 1.0
- 1.0
weight_number: 3
