bnn_fc1_index: '0'
bnn_fc2_index: '0'
bnn_fc3_index: '0'
bnn_weights_folder: /home/lpei/Workspace/code/neurosim/Data/BNN_weight
device_data_file: /home/lpei/Workspace/code/neurosim/Data/currents_vlsi.csv
frequency: 1e9
mode: Memory
nn_weights_folder: /home/lpei/Workspace/code/neurosim/Data/NN_weight
precision_mu: '1'
precision_sigma: '1'
sampling_times: '100'
technology: '0'
weight: A
