# constants.py

# Gate Types
INV = 0
NOR = 1
NAND = 2

# Transistor Types
NMOS = 0
PMOS = 1

# Transistor Size Constraints
MAX_NMOS_SIZE = 100
MIN_NMOS_SIZE = 2

# Transistor Region Heights
MAX_TRANSISTOR_HEIGHT = 28
MAX_TRANSISTOR_HEIGHT_FINFET = 34

# Layout Design Rules
MIN_GAP_BET_P_AND_N_DIFFS = 3.5
MIN_GAP_BET_SAME_TYPE_DIFFS = 1.6
MIN_GAP_BET_GATE_POLY = 2.8
MIN_GAP_BET_GATE_POLY_FINFET = 3.9
MIN_GAP_BET_CONTACT_POLY = 0.7
CONTACT_SIZE = 1.3
MIN_WIDTH_POWER_RAIL = 3.4
MIN_POLY_EXT_DIFF = 1.0
MIN_GAP_BET_FIELD_POLY = 1.6
POLY_WIDTH = 1.0
POLY_WIDTH_FINFET = 1.4

# Routing Pitch
M2_PITCH = 3.2
M3_PITCH = 2.8

# Leakage Ratios
AVG_RATIO_LEAK_2INPUT_NAND = 0.48
AVG_RATIO_LEAK_3INPUT_NAND = 0.31
AVG_RATIO_LEAK_2INPUT_NOR = 0.95
AVG_RATIO_LEAK_3INPUT_NOR = 0.62

# Sense Amplifier Transistor Widths
W_SENSE_P = 7.5
W_SENSE_N = 3.75
W_SENSE_ISO = 12.5
W_SENSE_EN = 5.0
W_SENSE_MUX = 9.0

# IR Drop and Region Ratios
IR_DROP_TOLERANCE = 0.25
LINEAR_REGION_RATIO = 0.20
HEIGHT_WIDTH_RATIO_LIMIT = 5
RATIO_READ_THRESHOLD_VS_VOLTAGE = 0.2

# Routing Modes
ROW_MODE = 0
COL_MODE = 1
